---
title: "ggplot_2"
author: "Daniel_Kim"
date: '2019 8 15 '
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
setwd("~/datacamp/ggplot"); gc()
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reticulate)
library(gridExtra)
use_python("C:/Anaconda3/python.exe")
```

#### Bar plots with color ramp

```{r, message=FALSE}
vocab <- read_csv("vocab.csv")
vocab$year <- as.integer(vocab$year)
vocab$sex <- as.factor(vocab$sex)
vocab$education <- as.factor(vocab$education)
vocab$vocabulary <- as.factor(vocab$vocabulary)
head(vocab)
```

```{r}
ggplot(vocab, aes(x = education, fill = vocabulary)) +
  geom_bar(position = "fill") +
  scale_fill_brewer()
```

- to solve the palette limitation problem ...

```{r}
blues <- RColorBrewer::brewer.pal(9, "Blues")
blue_range <- colorRampPalette(blues) 
```

- the `blue_range` is function...

```{r}
ggplot(vocab, aes(x = education, fill = vocabulary)) +
  geom_bar(position = "fill") + 
  scale_fill_manual(values = blue_range(11))
```

```{r}
mtcars$am <- as.factor(mtcars$am)
mtcars$cyl <- as.factor(mtcars$cyl)

ggplot(mtcars, aes(mpg, fill = am)) +
  geom_histogram(binwidth = 1) -> p1

ggplot(mtcars, aes(mpg, fill = am)) +
  geom_histogram(binwidth = 1,
  position = "dodge") -> p2

ggplot(mtcars, aes(mpg, fill = am)) +
  geom_histogram(binwidth = 1,
  position = "identity", alpha = .4) -> p3

ggplot(mtcars, aes(mpg, fill = cyl)) +
  geom_histogram(binwidth = 1,
  position = "identity", alpha = .4) -> p4

grid.arrange(p1, p2, p3, p4, ncol = 2)
```

### Line Plots

```{r}
data("economics")
head(economics)
```

```{r}
ggplot(economics, aes(date, unemploy)) + geom_line() -> p1
ggplot(economics, aes(date, unemploy/pop)) + geom_line() -> p2

gridExtra::grid.arrange(p1, p2)
```

```{r}
load(file="~/datacamp/ggplot/recess.RData")
head(recess)
```

```{r}
# Basic line plot
ggplot(economics, aes(x = date, y = unemploy/pop)) +
  geom_line() -> p1

# Expand the following command with geom_rect() to draw the recess periods
ggplot(economics, aes(x = date, y = unemploy/pop)) +
  geom_rect(data = recess,
         aes(xmax = begin, xmin = end, ymin = -Inf, ymax = Inf),
         inherit.aes = FALSE, fill = "red", alpha = 0.2) +
  geom_line() -> p2

grid.arrange(p1, p2)
```

```{r}
load("./fish.RData")
# head(fish.species)

fish.species %>%
  gather("Species", "Capture", -Year) -> fish.tidy

head(fish.tidy)
```

```{r}
ggplot(fish.tidy, aes(Year, Capture, col = Species)) + geom_line()
```

### qplot

```{r}
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() -> p1

qplot(wt, mpg, data = mtcars) -> p2

grid.arrange(p1, p2, ncol = 2)
```

```{r, message=FALSE}
# "Basic" dot plot, with geom_point():
ggplot(mtcars, aes(cyl, wt, col = am)) +
  geom_point(position = position_jitter(0.2, 0)) -> p1

# 1 - "True" dot plot, with geom_dotplot():
ggplot(mtcars, aes(cyl, wt, fill = am)) +
  geom_dotplot(binaxis = "y", stackdir = "center") -> p2

# 2 - qplot with geom "dotplot", binaxis = "y" and stackdir = "center"
qplot(
  cyl, wt,
  data = mtcars,
  fill = am,
  geom = "dotplot",
  binaxis = "y",
  stackdir = "center"
) -> p3

grid.arrange(p1, p2, p3, ncol = 3)
```

```{r}
# About group option...
ggplot(ChickWeight, aes(x = Time, y = weight, col = Diet)) +
  geom_line() -> p1

ggplot(ChickWeight, aes(x = Time, y = weight, col = Diet)) +
  geom_line(aes(group = Chick)) -> p2 # to draw one line per chick, 'group = Chick'

grid.arrange(p1, p2, ncol = 2)
```


```{r}
data("ChickWeight")
# map Diet onto col.
ggplot(ChickWeight, aes(x = Time, y = weight, col = Diet)) +
  geom_line(aes(group = Chick)) -> p1

# add geom_smooth()
ggplot(ChickWeight, aes(x = Time, y = weight, col = Diet)) +
  geom_line(aes(group = Chick), alpha = .3) + geom_smooth(lwd = 2, se = FALSE, alpha = .3) -> p2

grid.arrange(p1, p2, ncol = 2)
```
