---
title: "ggplot_1"
author: "Daniel_Kim"
date: '2019 8 15 '
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
setwd("~/datacamp/ggplot"); gc()
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reticulate)
library(gridExtra)
use_python("C:/Anaconda3/python.exe")
```


```{python}
import numpy as np
import pandas as pd

iris = r.iris
iris.plot()
```

```{r}
iris %>%
  as_tibble() %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, key = "Featrures", value = "value") %>%
  head()
```

```{r}
iris %>%
  as_tibble() %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure")) %>%
  spread(Measure, value) %>%
  select(-rowid) -> iris_wide

iris_wide %>% head()
```

```{r}
iris %>%
  mutate(Flower = (1:nrow(iris))) %>%
  gather(key, value, -Species, -Flower) %>%
  separate(key, c("Part", "Measure"), "\\.") %>%
  spread(Measure, value) -> iris.wide

iris.wide %>% head()
```


```{python}
iris_wide = r.iris_wide
iris_wide['Part'].value_counts()
```

```{python}
iris_wide.head()
```

```{python}
import matplotlib.pyplot as plt
plt.scatter(iris_wide['Length'], iris_wide['Width'], alpha=.5)
```

```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure")) %>%
  spread(Species, value) -> iris_tmp

iris_tmp %>% filter(!is.na(setosa)) %>% select(-versicolor, -virginica) -> iris_tmp_1
iris_tmp %>% filter(!is.na(versicolor)) %>% select(versicolor) -> iris_tmp_2
iris_tmp %>% filter(!is.na(virginica)) %>% select(virginica) -> iris_tmp_3

iris_tmp_1 %>%
  bind_cols(iris_tmp_2, iris_tmp_3) %>%
  select(-rowid) -> iris_wide_2

iris_wide_2 %>% head()
```

```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure")) %>%
  select(-rowid) -> iris_tidy

iris_tidy %>% head()
```

```{r}
iris %>%
  gather(key, Value, -Species) %>%
  separate(key, c("Part", "Measure"), "\\.") -> iris_tidy; iris_tidy %>% head()
```


```{r}
str(iris)
```

```{r}
str(iris_wide)
```

```{r}
str(iris_tidy)
```

```{r}
ggplot(iris_tidy, aes(x = Species, y = Value, col = Part)) + 
  geom_jitter() + 
  facet_grid(. ~ Measure)
```

```{r}
ggplot(iris_wide, aes(Length, Width, color = Part)) + geom_jitter() + facet_grid(. ~ Species)
```


```{r}
ggplot(mtcars, aes(x= wt, y = mpg, fill = cyl)) + geom_point(shape = 21, size = 4, alpha = .6) -> p1
ggplot(mtcars, aes(mpg, qsec, 
                   col = factor(cyl),
                   shape = factor(am),
                   size = (hp/wt))) + geom_point() -> p2
grid.arrange(p1, p2, ncol = 1)
```

```{r}
cyl.am <- ggplot(mtcars, aes(x = factor(cyl), fill = factor(am)))
```

```{r, message=FALSE}
library(gridExtra)
cyl.am + geom_bar(position = "stack") + ggtitle("stack") + 
  scale_x_discrete("Cylinders") + scale_y_continuous("Number") + 
  scale_fill_manual("Transmission", values = c('red', 'steelblue'), labels = c("Manual", "Automatic")) -> p1
cyl.am + geom_bar(position = "fill") + ggtitle("fill") -> p2
cyl.am + geom_bar(position = "dodge") + ggtitle("dodge") +
  scale_x_discrete("Cylinders") + scale_y_continuous("Number") + 
  scale_fill_manual("Transmission", values = c('red', 'steelblue'), labels = c("Manual", "Automatic")) -> p3
cyl.am + geom_bar() + ggtitle("default") -> p4

grid.arrange(p1, p2, p3, p4, ncol = 2)
```

```{r}
ggplot(mtcars, aes(x = mpg, y = 0)) +
  geom_jitter() +
  scale_y_continuous(limits=c(-2, 2))
```

## Scatter Plot
```{r}
ggplot(diamonds, aes(carat, price, col = clarity)) + geom_point() -> p1
ggplot(diamonds, aes(carat, price, col = clarity)) + geom_point(alpha = .3) -> p2

grid.arrange(p1, p2, ncol = 2)
```

```{r}
ggplot(diamonds, aes(clarity, carat, col = price)) + geom_point(alpha = .5) -> p1
ggplot(diamonds, aes(clarity, carat, col = price)) + geom_point(alpha = .5, position='jitter') -> p2

grid.arrange(p1, p2, ncol = 2)
```


## Histograms

```{r}
ggplot(mtcars, aes(x = mpg)) + geom_histogram() -> p1
ggplot(mtcars, aes(x = mpg)) + geom_histogram(binwidth = 1) -> p2
ggplot(mtcars, aes(x = mpg)) + geom_histogram(binwidth = 1, aes(y = ..density..)) -> p3
ggplot(mtcars, aes(x = mpg, y = ..density..)) + geom_histogram(binwidth = 1, fill = "steelblue") -> p4

grid.arrange(p1, p2, p3, p4, ncol = 2)
```


















