---
title: "R Notebook"
output: html_notebook
---

```{r}
iris.wide
```

```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width , Petal.Length, Petal.Width, key = "Features", value = "value")
```


```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width , Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure"))
```


```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width , Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure")) %>%
  spread(Measure, value) %>%
  select(-rowid) -> iris_wide

iris_wide
```

```{python}
import numpy as np
import pandas as pd
iris_wide = r.iris_wide

iris_wide.head()
```

```{python}
iris_wide.shape
```


```{r}
iris %>%
  rowid_to_column() %>%
  gather(Sepal.Length, Sepal.Width , Petal.Length, Petal.Width, key = "Features", value = "value") %>%
  separate(Features, sep = "\\.", into = c("Part", "Measure")) %>%
  spread(Species, value) -> iris_tmp

```

```{r}
iris_tmp %>%
  filter(!is.na(setosa)) %>%
  select(-versicolor, -virginica) -> df.setosa

iris_tmp %>%
  filter(!is.na(versicolor)) %>%
  select(versicolor) -> df.versicolor

iris_tmp %>%
  filter(!is.na(virginica)) %>%
  select(virginica) -> df.virginica

df.setosa %>%
  bind_cols(df.versicolor) %>%
  bind_cols(df.virginica) %>%
  select(-rowid) -> iris_wide_2
```


```{python}
iris_wide_2 = r.iris_wide_2
iris_wide_2
```

```{r}

```


```{r}

```

