---
title: "Scope and User defined functions"
author: "Daniel_Kim"
date: '2019 8 15 '
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
setwd("~/datacamp/Python_DS_toolbox_part1/")
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reticulate)
use_python("C:/Anaconda3/python.exe")
```

 - Global Scope, Local Scope, Built-in Scope....
 
```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def square(value):
  """Return the square of a number"""
  new_val = value**2
  return new_val
  
square(3)
```

```{python}
new_val = 20


def square(value):
  """Return the square of a number"""
  new_value2 = new_val**2
  return new_value2
  
square(3)
```

```{python}
num = 5
```


```{python}
def func1():
  num = 3
  print(num)
```

```{python}
def func2():
  global num
  double_num = num * 2
  num = 6
  print(double_num)
```

```{python}
func1()
```

```{python}
func2()
```

```{python}
team = "teen titans"

def change_team():
  """Change the value of the global variable team."""
  
  # Use team in global scope
  global team
  
  # Change the value of team in global: team
  team = "justice league"
```

```{python}
print(team)
```

```{python}
change_team()
```

 - `change_team()` changes the value of the name team!
```{python}
print(team)
```

- Python builtin scope...
```{python}
import builtins

dir(builtins)
```

## Nested functions...

```{python}
def raise_val(n):
  """Return the inner functions"""
  
  def inner(x):
    """Raise x to the power of n."""
    raised = x ** n
    return raised
    
  return inner
```


```{python}
square = raise_val(2)
cube = raise_val(3)
print(square(2), cube(3))
```

 - Using nonlocal

```{python}
def outer():
  """Print the value of n."""
  n = 1
  
  def inner():
    nonlocal n
    n = 2
    print(n)
    
  inner()
  print(n)
```


```{python}
outer()
```


```{python}
def three_shouts(word1, word2, word3):
  """Return a tuple of strings concatenated with '!!!'"""
  
  # Define inner
  def inner(word):
    """Return a string concatenated with '!!!'."""
    return word + '!!!'
    
  # Return a tuple of strings
  return (inner(word1), inner(word2), inner(word3))
```


```{python}
print(three_shouts('a', 'b', 'c'))
```

```{python}
def echo(n):
  """Return the inner_echo function."""
  
  # Define inner_echo
  def inner_echo(word1):
    """Concatenate n copies of word1..."""
    echo_word = word1 * n
    return echo_word
    
  # Return inner_echo
  return inner_echo
```

```{python}
# Call echo twice
twice = echo(2)
```

```{python}
thrice = echo(3)
```


```{python}
print(twice('hello'), thrice('hello'))
```


```{python}
# Define echo_shout()
def echo_shout(word):
  """Change the value of a nonlocal variable."""
  
  # Concatenate word with itself: echo_word
  echo_word = word*2
  
  # Print echo_word
  print(echo_word)
  
  # Define inner function shout()
  def shout():
    """Alter a variable in the enclosing scope."""
    # Use echo_word in nonlocal scope
    nonlocal echo_word
  
    # Change echo_word to echo_word concatenated with '!!!'
    echo_word = echo_word + '!!!'
  
  # Call function shout()
  shout()
  
  # Print echo_word()
  print(echo_word)
```


```{python}
# Call function echo_shout() with argument 'hello'
echo_shout('hello')
```

## Default and flexible arguments

```{python}
# Define shout_echo
def shout_echo(word1, echo = 1):
  """Concatenate echo copies of word1 ad three exclamination marks at the end
  of the string."""
  
  # Concatenate echo copies of word1 using *: echo_word
  echo_word = word1 * echo
  
  # Concatenate '!!!' to echo_word: short_word
  shout_word = echo_word + '!!!'
  
  # Return shout_word
  return shout_word
  
# Call shout_echo() with 'Hey': no_echo
no_echo = shout_echo('Hey')

# Call shout_echo() with 'Hey' and echo = 5: with_echo
with_echo = shout_echo('Hey', echo=5)
```


```{python}
print(no_echo)
print(with_echo)
```


```{python}
# Define shout echo
def shout_echo(word1, echo = 1, intense = False):
  """Concatenate echo copies of word1 and three exclamination marks at the end of the string."""
  
  # Concatenate echo copies of word1 using * : echo_word
  echo_word = word1 * echo
  
  # Make echo_word uppercase if intense is True
  if intense is True:
    # Make uppercaes andn concatenate '!!!' : echo_word_new
    echo_word_new = echo_word.upper() + '!!!'
  else:
    # Concatenate '!!!' to echo_word: echo_word_new
    echo_word_new = echo_word + '!!!'
    
  # return echo_word_new
  return echo_word_new
```


```{python}
# Call shout_echo() with 'Hey', echo=5 and intense= True
shout_echo('Hey', echo=5, intense = True)
```


```{python}
# Call shout_echo() with 'Hey' and intense = True
shout_echo('Hey', intense = True)
```

- `*args`
```{python}
# Define gibberish
def gibberish(*args):
  """Concatenate strings in *args together."""
  
  # Initialize an empty string; hodgepodge
  hodgepodge = ''
  
  # Concatenate the strings in args
  for word in args:
    hodgepodge += word
  
  # Return hodgepodge
  return hodgepodge
```


```{python}
# Call gibberish() with one string: one_word
gibberish("luke")
```

```{python}
many_words = gibberish("luke", "leia", "han", "obi", "darth")

gibberish(many_words)
```

- Functions with variable-length keyword arguments(`**kwargs`)
```{python}
# Define report_status
def report_status(**kwargs):
  """Print out the status of a movie character."""
  print("\nBEGIN: REPORT\n")
  
  # Iterate over the key-value pairs of kwargs
  for key, value in kwargs.items():
    # Print out the keys and values, seperated by a colon ':'
    print(key + ": " + value)
    
  print("\nEND REPORT")
```


```{python}
report_status(name="luke", affiliation = "jedi", status="missing")
```


```{python}
report_status(name="anakin", affiliation="sith lord", status = "deceased")
```


```{python}
# Define count_entries()
def count_entries(df, col_name="lang"):
  """Return a dictionary with counts of occurrences as value for each key."""
  
  # Initialize an empty dictionary: cols_count
  cols_count = {}
  
  # Extract column from DataFrame: col
  col = df[col_name]
  
  # Iterate over the column in DataFrame
  for entry in col:
    
    # If entry is in cols_counts, add 1
    if entry in cols_count.keys():
      cols_count[entry] += 1
      
    # Else add the entry to cols_count, set the value to 1
    else:
      cols_count[entry] = 1
      
  # Return the cols_count dictionary
  return cols_count
```


```{r}
data(iris)
data(mtcars)
```


```{python}
result1 = count_entries(r.iris, 'Species')
result1
```


```{python}
# Define count_entries()
def count_entries(df, *args):
  """Return a dictionary with counts of occurance as value for each key."""
  
  # Initialize an empty dictionary: cols_count
  cols_count = {}
  
  # Iterate over column names in args
  for col_name in args:
  
    # Extract column from DataFrame: col
    col = df[col_name]
    
    # Iterate over the column in DataFrame
    for entry in col:
    
      # If entry in cols_count, add 1
      if entry in cols_count.keys():
        cols_count[entry] += 1
        
      # Else add the entry to cols_count, set the value to 1
      else:
        cols_count[entry] = 1
  
  # Return the cols_count dictionary
  return cols_count
```

```{python}
count_entries(r.mtcars, 'cyl', 'gear')
```

